# Generated by Django 5.2.9 on 2026-02-19 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_predefined', models.BooleanField(default=False, help_text='Predefined packages cannot be deleted by users.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leave Package',
                'verbose_name_plural': 'Leave Packages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeavePackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Vacation Leave', 'Vacation Leave'), ('Sick Leave', 'Sick Leave'), ('Birthday Leave', 'Birthday Leave'), ('Solo Parent Leave', 'Solo Parent Leave'), ('Bereavement Leave', 'Bereavement Leave'), ('Paternity Leave', 'Paternity Leave'), ('Maternity Leave', 'Maternity Leave')], max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Number of leave days allocated for this leave type.', max_digits=5)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='employee_packages.leavepackage')),
            ],
            options={
                'verbose_name': 'Leave Package Item',
                'verbose_name_plural': 'Leave Package Items',
                'ordering': ['leave_type'],
                'unique_together': {('package', 'leave_type')},
            },
        ),
    ]
