# Generated by Django 5.1.7 on 2025-06-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=50, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("suffix", models.CharField(blank=True, max_length=10, null=True)),
                ("nickname", models.CharField(blank=True, max_length=50, null=True)),
                ("present_address", models.TextField()),
                ("provincial_address", models.TextField(blank=True, null=True)),
                (
                    "telephone_no",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("mobile_no", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("birth_date", models.DateField()),
                ("birth_place", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("citizenship", models.CharField(default="Filipino", max_length=100)),
                (
                    "civil_status",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("Married", "Married"),
                            ("Widowed", "Widowed"),
                            ("Separated", "Separated"),
                            ("Divorced", "Divorced"),
                        ],
                        max_length=20,
                    ),
                ),
                ("height", models.CharField(blank=True, max_length=10, null=True)),
                ("weight", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "ss_no",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="SSS Number"
                    ),
                ),
                (
                    "tin_no",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="TIN Number"
                    ),
                ),
                (
                    "philhealth_no",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="PhilHealth Number",
                    ),
                ),
                (
                    "pagibig_no",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Pag-IBIG Number",
                    ),
                ),
                (
                    "spouse_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "spouse_occupation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "spouse_company",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "father_occupation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "father_company",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mother_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mother_occupation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mother_company",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "highest_degree",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "school_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "course_or_program",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "year_graduated",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("date_hired", models.DateField()),
                ("profile_image", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("awarding_body", models.CharField(max_length=255)),
                ("date_awarded", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeDependent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("occupation", models.CharField(blank=True, max_length=255, null=True)),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("relationship", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Elementary", "Elementary"),
                            ("Secondary", "Secondary"),
                            ("Vocational", "Vocational"),
                            ("Bachelor", "Bachelor"),
                            ("Master", "Master"),
                            ("Doctorate", "Doctorate"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("school", models.CharField(max_length=255)),
                ("course", models.CharField(blank=True, max_length=255, null=True)),
                ("year_started", models.CharField(max_length=10)),
                ("year_ended", models.CharField(max_length=10)),
                ("graduated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["year_started"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("rating", models.CharField(blank=True, max_length=50, null=True)),
                ("date_taken", models.DateField()),
                ("license_no", models.CharField(blank=True, max_length=100, null=True)),
                ("issued_date", models.DateField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_flexible", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeSibling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("occupation", models.CharField(blank=True, max_length=255, null=True)),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
