# Generated by Django 5.1.7 on 2025-06-16 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="organizations.department",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="office",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="organizations.office"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="organizations.position"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organizations.program",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employeeaward",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="awards",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="employeedependent",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dependents",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="employeeeducation",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_education",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="employeelicense",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="licenses",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="employeeschedule",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="employeesibling",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="siblings",
                to="employees.employee",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employeeschedule",
            unique_together={("employee", "day_of_week")},
        ),
    ]
