# Generated by Django 5.1.7 on 2025-06-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="password_hash",
            field=models.CharField(
                blank=True,
                help_text="Hashed password for API authentication",
                max_length=128,
                null=True,
            ),
        ),
    ]
