# Generated by Django 5.2.9 on 2026-02-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_hr',
            field=models.BooleanField(default=False, help_text='Indicates if the employee is part of HR department with special permissions.'),
        ),
    ]
