# Generated by Django 5.1.7 on 2025-06-16 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeavePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("Vacation Leave", "Vacation Leave"),
                            ("Sick Leave", "Sick Leave"),
                            ("Birthday Leave", "Birthday Leave"),
                            ("Solo Parent Leave", "Solo Parent Leave"),
                            ("Bereavement Leave", "Bereavement Leave"),
                            ("Paternity Leave", "Paternity Leave"),
                            ("Maternity Leave", "Maternity Leave"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("days_allowed", models.IntegerField()),
                ("description", models.TextField()),
                ("requires_approval", models.BooleanField(default=True)),
                ("requires_documentation", models.BooleanField(default=False)),
                ("applicable_positions", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["leave_type"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("Vacation Leave", "Vacation Leave"),
                            ("Sick Leave", "Sick Leave"),
                            ("Birthday Leave", "Birthday Leave"),
                            ("Solo Parent Leave", "Solo Parent Leave"),
                            ("Bereavement Leave", "Bereavement Leave"),
                            ("Paternity Leave", "Paternity Leave"),
                            ("Maternity Leave", "Maternity Leave"),
                        ],
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("days_requested", models.IntegerField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                ("approval_notes", models.TextField(blank=True, null=True)),
                ("supporting_documents", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leaves",
                        to="employees.employee",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("Vacation Leave", "Vacation Leave"),
                            ("Sick Leave", "Sick Leave"),
                            ("Birthday Leave", "Birthday Leave"),
                            ("Solo Parent Leave", "Solo Parent Leave"),
                            ("Bereavement Leave", "Bereavement Leave"),
                            ("Paternity Leave", "Paternity Leave"),
                            ("Maternity Leave", "Maternity Leave"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "accrued_this_year",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "used_this_year",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "pending_requests",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["employee", "leave_type"],
                "unique_together": {("employee", "leave_type")},
            },
        ),
        migrations.CreateModel(
            name="LeaveCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("Vacation Leave", "Vacation Leave"),
                            ("Sick Leave", "Sick Leave"),
                            ("Birthday Leave", "Birthday Leave"),
                            ("Solo Parent Leave", "Solo Parent Leave"),
                            ("Bereavement Leave", "Bereavement Leave"),
                            ("Paternity Leave", "Paternity Leave"),
                            ("Maternity Leave", "Maternity Leave"),
                        ],
                        max_length=50,
                    ),
                ),
                ("year", models.IntegerField()),
                ("total_credits", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "used_credits",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "remaining_credits",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_credits",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "leave_type"],
                "unique_together": {("employee", "leave_type", "year")},
            },
        ),
    ]
