# Generated by Django 5.2.9 on 2026-02-03 03:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_employee_password_hash'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique identifier for the permission (e.g., 'can_approve_leave')", max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Permission code must be lowercase alphanumeric with underscores, starting with a letter', regex='^[a-z][a-z0-9_]*$')])),
                ('name', models.CharField(help_text='Human-readable name for the permission', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this permission allows')),
                ('category', models.CharField(choices=[('leave', 'Leave Management'), ('employee', 'Employee Management'), ('reports', 'Reports & Analytics'), ('settings', 'System Settings'), ('organization', 'Organization Management'), ('audit', 'Audit & Compliance')], default='settings', help_text='Category for grouping permissions in the UI', max_length=50)),
                ('is_system', models.BooleanField(default=False, help_text='System permissions cannot be deleted by HR')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive permissions are not enforced')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PermissionModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name for UI display', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order in the UI')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='modules', to='rbac.permission')),
            ],
            options={
                'verbose_name': 'Permission Module',
                'verbose_name_plural': 'Permission Modules',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RBACChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('assign', 'Role Assigned'), ('revoke', 'Role Revoked'), ('grant', 'Permission Granted'), ('deny', 'Permission Denied')], max_length=20)),
                ('model_type', models.CharField(choices=[('permission', 'Permission'), ('role', 'Role'), ('role_permission', 'Role Permission'), ('employee_role', 'Employee Role')], max_length=20)),
                ('model_id', models.IntegerField()),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('affected_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbac_changes_received', to='employees.employee')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbac_audit_logs', to='employees.employee')),
            ],
            options={
                'verbose_name': 'RBAC Change Log',
                'verbose_name_plural': 'RBAC Change Logs',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for the role', max_length=255, unique=True)),
                ('code', models.CharField(help_text="Unique code identifier (e.g., 'HR_ADMIN', 'DEAN')", max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Role code must be uppercase alphanumeric with underscores, starting with a letter', regex='^[A-Z][A-Z0-9_]*$')])),
                ('description', models.TextField(blank=True, help_text="Description of this role's responsibilities")),
                ('level', models.IntegerField(choices=[(-1, 'Super Admin (HR)'), (0, 'Executive (VPAA)'), (1, 'Department Head (Dean)'), (2, 'Program Head (Chair)'), (3, 'Senior Staff'), (4, 'Staff'), (5, 'Basic User'), (99, 'Guest/Limited')], default=5, help_text='Hierarchical level for approval chain (lower = higher authority)')),
                ('approval_scope', models.CharField(choices=[('none', 'No Approval Rights'), ('program', 'Program Level'), ('department', 'Department Level'), ('organization', 'Organization Level'), ('all', 'Global Access')], default='none', help_text='What scope of items can this role approve', max_length=20)),
                ('is_system', models.BooleanField(default=False, help_text='System roles cannot be deleted by HR')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive roles are not enforced')),
                ('can_be_assigned', models.BooleanField(default=True, help_text='Whether this role can be assigned to new employees')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roles', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this permission grant is currently active')),
                ('conditions', models.JSONField(blank=True, help_text="Optional JSON conditions for this permission (e.g., {'max_amount': 10000})", null=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to='employees.employee')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='rbac.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='rbac.role')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', through='rbac.RolePermission', to='rbac.permission'),
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text="Primary role determines the employee's main dashboard view")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role assignment is currently active')),
                ('valid_from', models.DateTimeField(blank=True, help_text='When this role assignment becomes active (null = immediately)', null=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='When this role assignment expires (null = never)', null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this role assignment')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to='employees.employee')),
                ('department_scope', models.ForeignKey(blank=True, help_text='Limit this role to a specific department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoped_roles', to='organizations.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_roles', to='employees.employee')),
                ('program_scope', models.ForeignKey(blank=True, help_text='Limit this role to a specific program', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoped_roles', to='organizations.program')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='rbac.role')),
            ],
            options={
                'verbose_name': 'Employee Role',
                'verbose_name_plural': 'Employee Roles',
                'ordering': ['-is_primary', 'role__level'],
                'unique_together': {('employee', 'role', 'department_scope', 'program_scope')},
            },
        ),
    ]
